### ISSUE TITLE
merge with conventional-recommended-workflow

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-changelog#2]
I'm going to start merging together the functionality of this repo and `conventional-recommended-workflow`, so that we can release a one-step `standard-changelog` bin. which handles:
- [ ] Bumping version in package.json
- [x] applying conventionalChangelog.
- [ ] Commiting package.json and CHANGELOG.md files
- [ ] Tagging.
- [ ] Pushing (optionally).
- [ ] Publishing (optionally).

@feross we would love to work with you to make this the tool that you use for managing `standard`'s changelog, are you comfortable with the [angular commit format](https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md)? any other features that you're itching for?

Would love feedback (CC: @nexdrew, @stevemao) what am I missing.

**Comment by stevemao** [comment]
You might wanna scrap all the code and docs here as they were copied from `conventional-changelog` and `conventional-changelog-cli`(plus very outdated :stuck_out_tongue_closed_eyes: ). The scope of this module is completely changed too :)

**Comment by feross** [comment]
@bcoe  The [`standard` changelog](https://github.com/feross/standard/blob/master/CHANGELOG.md) is pretty barebones. The features in your list sound fine to me.

**Comment by stevemao** [comment]
@feross The docs @bcoe linked is more from the tools perspective rather than committer's. https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines and   https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit# is what you wanna read :)

**Comment by stevemao** [comment]
Closing as we will keep the original scope
