### ISSUE TITLE
can we retire this repo?

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-changelog#6]
can we retire this repository in favor of `standard-version`? seems like there's a lot of overlap between the two.

**Comment by stevemao** [comment]
So this one should just generate the changelog based on angular convention, and `standard-version` does something more. Eventually `standard-version` will depend on `standard-changelog`. We could write some script to keep it update-to-date with `conventional-changelog` and `conventional-changelog-cli`.

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-changelog/issues/149

If we use `peerDepdencies` for presets, we can retire this repo.
